services:
  thingino-image-builder-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thingino-image-builder-dev
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=America/New_York
    volumes:
      - .:/home/thingino/bin
      - /sys:/sys
      - /run:/run
      - /dev:/dev
    command: ["sleep","infinity"]
